In [1]:
import pandas as pd

In [3]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia', 2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340]
]

columns = [
    'Make',
    'Model',
    'Year',
    'Engine HP',
    'Engine Cylinders',
    'Transmission Type',
    'Vehicle_Style',
    'MSRP'
]

df = pd.DataFrame(data = data, columns=columns)

df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [4]:
# load a list in pandas series
data = [1, 2, 3, 4, 5]
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# load a dictionary in panda series
# important: pandas series e dictionary diye data load korle dictionary er value single hole list er proyojon nai. but ekta row te multiple value thakle list use korte hobe. 

data = {
    'a': [10, 20, 30], 
    'b': 20, 
    'c': 30
    }
pd.Series(data=data)

a    [10, 20, 30]
b              20
c              30
dtype: object

In [8]:
# load a list in pandas dataframe -1
data = [[1, 2, 3], [4, 5, 6]]
pd.DataFrame(data=data)

   0  1  2
0  1  2  3
1  4  5  6

In [9]:
# load a list in pandas dataframe -2
data = [[1, 2, 3], [4, 5, 6]]
pd.DataFrame(data=data, columns=['a', 'b', 'c'], index=['row1', 'row2'])

      a  b  c
row1  1  2  3
row2  4  5  6

In [ ]:
# load a dictionary in dataframe
# important: dataframe e dictionary te single value holew must list use korte hobe.
data = {
    'a': [1, 2, 3], 
    'b': [4, 5, 6], 
    'c': [7, 8, 9]
    }

index = ['row1', 'row2', 'row3']
pd.DataFrame(data=data, index=index)

      a  b  c
row1  1  4  7
row2  1  5  8
row3  1  6  9