In [1]:
import pandas as pd

In [4]:
# load a list in pandas series
data = [1, 2, 3, 4, 5]
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# load a dictionary in panda series
# important: pandas series e dictionary diye data load korle dictionary er value single hole list er proyojon nai. but ekta row te multiple value thakle list use korte hobe. 

data = {
    'a': [10, 20, 30], 
    'b': 20, 
    'c': 30
    }
pd.Series(data=data)

a    [10, 20, 30]
b              20
c              30
dtype: object

In [8]:
# load a list in pandas dataframe -1
data = [[1, 2, 3], [4, 5, 6]]
pd.DataFrame(data=data)

   0  1  2
0  1  2  3
1  4  5  6

In [9]:
# load a list in pandas dataframe -2
data = [[1, 2, 3], [4, 5, 6]]
pd.DataFrame(data=data, columns=['a', 'b', 'c'], index=['row1', 'row2'])

      a  b  c
row1  1  2  3
row2  4  5  6

In [ ]:
# load a dictionary in dataframe
# important: dataframe e dictionary te single value holew must list use korte hobe.
data = {
    'a': [1, 2, 3], 
    'b': [4, 5, 6], 
    'c': [7, 8, 9]
    }

index = ['row1', 'row2', 'row3']
pd.DataFrame(data=data, index=index)

      a  b  c
row1  1  4  7
row2  1  5  8
row3  1  6  9

'\nকোনো নতুন ডেটাসেট হাতে পাওয়ার পর সবসময় এই তিনটি কাজ সবার আগে করবেন:\n১. df.shape দিয়ে সাইজ দেখবেন।\n২. df.head() দিয়ে ডেটা কেমন তা বোঝার চেষ্টা করবেন।\n৩. df.info() ব্যবহার করবেন। এটি ডেটাসেটের প্রতিটি কলামের ডেটা টাইপ এবং কোনো ভ্যালু মিসিং (Null) আছে কি না, তা বলে দেয়।\n'